compile:
  stage: build
  script:
    - ci/build.sh
  artifacts:
    paths:
      - target/*.jar

deploy-staging:
  stage: deploy
  environment:
    name: staging
    url: https://newsletter.plapadoo.de
  only:
    - master
  script:
    - ci/deploy-staging.sh
